os: osx
language: objective-c
sudo: false
install: true
script: xcodebuild -project V2RayX.xcodeproj -target V2RayX -configuration Release

before_deploy:
- cd build/Release/
- zip -r V2RayX.app.zip V2RayX.app
- cd ../..

deploy:
  provider: releases
  api_key:
    secure: Bd+d2S6+Fho1pq+n+XMMtMavswcZyI4bfVUaKbNqsDaK2rbM0EgC4CSV7xv8xyUbwqbyt0iCVANkwsHHxRrLtP20T+pGlENwmOsQGDVvMjW1kJHnenGiGwcEepKUGAvJTyc4HhzTEKjUlPveX5LeZeY2nB9SgopI8UGsSaj6hD4jE80A7Q8ZLWf0V6bKbI0Sqyfjrx6ZZB4zIav0961beBV5MI7ajxx8hX7TcLf9pkZoIcsHg+dDJvv3qphIRo6nXtUXaE6qfYmJJs0+p1YLxFSKNZ3o5017Yt2mqB1Al+8vADyZmKIGv2r89otvepQyhX0osQ8GN22snbpCiIQxVUOW84q9DGT7WVtmO75fqMD8w/OvBch2pNkmZDm21ZWY6iz0yJx4UgkMHYWMG/z6MVseLIO41VOkHrcnwTKSeae7wM+QiIlRJeq0A9BvrJhmCf9wVkCNtfRgnXNyjtHw24UMTqPk3xnAnCh9Yq37Ctzx9UDnNrmQxNHrtVURYWN0wQia1QQ54bkhiqWK/b02FkJmOhfKKUkSw4mIWI2pNITU5XrPJ6VRYVRXdYAJC3vtbREuQ1yNr3Jul/HQtJUS31oXilHjupjuT30Hvu2S2p5CAEsPj5nChnETVknxu6jdCay0lM6SbCWKkgQxs+qYab4DO9OnuDvnGNnDz1nJ+fM=
  file: build/Release/V2RayX.app.zip
  skip_cleanup: true
  on:
    repo: 2873tr6x/V2RayX
    tags: true
